#!/bin/sh

echo "have you run stow yet? (y/n)"

read decision

if [ "$decision" = "y" ]; then
    echo "make sure you have yay installed, sleeping 5 seconds" && sleep 5
elif [ "$decision" = "n" ]; then
    echo "please stow first then run this script" && exit
else
    echo "accepted answers are y/n" && exit
fi

yay -S --needed wget stow dunst obmenu-generator openbox picom tint2 feh network-manager-applet polkit-gnome volctl alsa-utils vimix-gtk-themes xdotool i3lock-color flameshot numlockx redshift ttf-roboto lxappearance opensnap galendae-git gtk2-perl lxappearance-obconf gnome-keyring papirus-icon-theme ttf-roboto-mono ttf-roboto-slab alacritty pcmanfm brave-bin rofi zsh zsh-syntax-highlighting pulseaudio pulseaudio-alsa jmtpfs seahorse shell-color-scripts pacman-contrib cronie xorg neovim qt5ct kvantum-qt5 pavucontrol unclutter openssh noto-fonts-cjk noto-fonts-emoji htop curl git conky file-roller p7zip unrar neofetch

wget https://cdn.discordapp.com/attachments/835125164572016661/842410994840240198/Afterpiece.tar.gz

tar xzf Afterpiece.tar.gz

mkdir ~/.themes

mv Afterpiece ~/.themes

wget https://cdn.discordapp.com/attachments/835125164572016661/842410320160882728/165371-Breeze.tar.gz

tar xzf 165371-Breeze.tar.gz

mkdir ~/.icons

mv Breeze ~/.icons

touch "$HOME/.cache/zshhistory"

chsh $USER

sudo sed -i "31i Path askpass /usr/lib/seahorse/ssh-askpass" /etc/sudo.conf

git clone https://github.com/deennyy/other-configs

sudo cp -f other-configs/usr/share/applications/* /usr/share/applications

mkdir -p ~/.config/pulse

cp other-configs/home/user/.config/pulse/daemon.conf ~/.config/pulse

sudo sh -c "echo 'source /home/denny/.config/nvim/init.vim' >> /etc/xdg/nvim/sysinit.vim"

sudo mkdir -p /etc/X11/xorg.conf.d

sudo cp other-configs/etc/X11/xorg.conf.d/10-monitor.conf /etc/X11/xorg.conf.d

sudo cp other-configs/etc/X11/xorg.conf.d/50-mouse-acceleration.conf /etc/X11/xorg.conf.d

git clone https://github.com/vinceliuice/vimix-kde

mkdir -p ~/.config/Kvantum/Vimix-Dark-Doder

cp vimix-kde/Kvantum/Vimix-Dark-Doder/* ~/.config/Kvantum/Vimix-Dark-Doder

sudo sh -c "echo 'QT_QPA_PLATFORMTHEME=qt5ct' >> /etc/environment"

sudo ln -s /usr/share/fontconfig/conf.avail/10-sub-pixel-rgb.conf /etc/fonts/conf.d/

sudo ln -s /usr/share/fontconfig/conf.avail/11-lcdfilter-default.conf /etc/fonts/conf.d/

#sudo sh -c "echo 'export FREETYPE_PROPERTIES=\"truetype:interpreter-version=38\"' >> /etc/profile.d/freetype2.sh"

sudo fc-cache -fv

sudo systemctl enable --now fstrim.timer

sudo systemctl enable --now paccache.timer

sudo systemctl enable --now cronie

sudo systemctl enable --now systemd-timesyncd

sudo systemctl enable --now sshd

sudo cp -f other-configs/etc/pacman.conf /etc

sudo pacman -Syu

#sudo cp -f other-configs/etc/default/grub /etc/default

#sudo grub-mkconfig -o /boot/grub/grub.cfg

sudo sh -c "echo 'vm.swappiness=10' >> /etc/sysctl.d/99-swappiness.conf"

sudo sh -c "echo 'needs_root_rights = no' >> /etc/X11/Xwrapper.config"

echo "would you like to copy hardware specific configs? (nvidia stuff) [y/n]"

read decision2

if [ "$decision2" = "y" ]; then
    echo "X11 likely wont start for you, as the nvidia config is highly specific for me, delete it if you're having problems"
    echo "also the gamemode config has a GPU OC applied, which might crash on your GPU, be sure to disable it"
    echo "sleeping 5 seconds..." && sleep 5
elif [ "$decision2" = "n" ]; then
    exit
else
    echo "accepted answers are y/n" && exit
fi

sudo pacman -S --needed nvidia-dkms nvidia-utils nvidia-settings vulkan-icd-loader

sudo cp other-configs/etc/X11/xorg.conf.d/20-nvidia.conf /etc/X11/xorg.conf.d

sudo mkdir -p /etc/pacman.d/hooks

sudo cp other-configs/etc/pacman.d/hooks/nvidia.hook /etc/pacman.d/hooks

sudo cp other-configs/etc/gamemode.ini /etc

sudo cp -f other-configs/etc/makepkg.conf /etc

sudo cp -f other-configs/etc/mkinitcpio.conf /etc

sudo mkinitcpio -P

echo "enable autologin? (username is set to denny)"

read decision3

if [ "$decision3" = "y" ]; then
    sleep 1
elif [ "$decision3" = "n"]; then
    exit
else
    echo "accepted answers are y/n" && exit
fi

sudo mkdir -p /etc/systemd/system/getty@tty1.service.d

sudo sh -c "echo -e '[Service]\nExecStart=\nExecStart=-/usr/bin/agetty --skip-login --nonewline --noissue --autologin denny --noclear %I \$TERM\nType=simple' >> /etc/systemd/system/getty@tty1.service.d/override.conf"

touch ~/.hushlogin
